### ISSUE TITLE
I can't not find "*.extraInfo.dat" file in Dataset

### ISSUE THREAD

**Issue by hyeonwoocho7** [JohanYe/VF-Net#3]
I try to run your code with FDI 16 dataset which you shared, but code is not run because there is no "extraInfo.dat" file in FDI 16 dataset. I want to run your code. Please, share your dataset or tips.

**Comment by JohanYe** [comment]
My apologies, these have been renamed to *_curvature_edgedistance.dat" files in the final dataset release. 
My latest commit should fix this issue, otherwise please let me know.
