### ISSUE TITLE
Error in running main.py 

### ISSUE THREAD

**Issue by hyeonwoocho7** [JohanYe/VF-Net#4]
I ran main.py for VF-Net training, but an error occurred because the "static_kl" and "iwae_k" arguments were missing. After adding the arguments as shown below to main.py, it worked without any issues.

![image](https://github.com/JohanYe/VF-Net/assets/102580131/cd1fe970-fe77-4899-85e4-e3b37f44f7ee)

**Comment by JohanYe** [comment]
Thank you for letting me know, i have pushed a fix. Please note that the static_kl value should have been 0 to reproduce my results, but it should no longer be necessary
